version: 2
jobs:
    build:
        docker:
            - image: mumblepins/wix-toolset:latest
        steps:
            - checkout
            - run: |
                set -x
                ant resolve
                ant fatjar
                ant msi
                ant deb
            
            - store_artifacts:
                path: dist
